# roles/account/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "/etc/gridinit.d/{{ openio_account_namespace }}"
    - path: "{{ openio_account_sysconfig_dir }}/{{ openio_account_servicename }}"
    - path: "/etc/oio/sds/{{ openio_account_namespace }}/watch"
    - path: "/var/log/oio/sds/{{ openio_account_namespace }}/{{ openio_account_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0750"
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "account.conf.j2"
      dest: "{{ openio_account_sysconfig_dir }}/\
        {{ openio_account_servicename }}/{{ openio_account_servicename }}.conf"
    - src: "gridinit_account.conf.j2"
      dest: "{{ openio_account_gridinit_dir }}/{{ openio_account_gridinit_file_prefix }}\
        {{ openio_account_servicename }}.conf"
    - src: "watch-account.yml.j2"
      dest: "{{ openio_account_sysconfig_dir }}/watch/{{ openio_account_servicename }}.yml"
  register: _account_conf

- name: "restart account to apply the new configuration"
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{ openio_account_namespace }}-{{ openio_account_servicename }}
  register: _restart_account
  when:
    - _account_conf is changed
    - not openio_account_provision_only
  tags: configure

- block:
    - name: "Ensure account is started"
      command: gridinit_cmd start {{ openio_account_namespace }}-{{ openio_account_servicename }}
      register: _start_account
      changed_when: '"Success" in _start_account.stdout'
      when:
        - not openio_account_provision_only
        - _restart_account is skipped
      tags: configure

    - name: check account
      uri:
        url: "http://{{ openio_account_bind_address }}:{{ openio_account_bind_port }}/status"
        return_content: true
        status_code: 200
      register: _account_check
      retries: 3
      delay: 5
      until: _account_check is success
      changed_when: false
      when:
        - not openio_account_provision_only
  when: openio_bootstrap | d(false)
...
