# roles/account/tasks/main.yml
---
- name: "Include {{ ansible_distribution }} variables"
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: "Include {{ ansible_distribution }} tasks"
  include_tasks: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution }}.yml"
    - "{{ ansible_os_family }}.yml"
  tags: install

- name: Ensure directories exists
  file:
    path: "{{ item.path }}"
    state: directory
    owner: "{{ item.owner | default('openio') }}"
    group: "{{ item.group | default('openio') }}"
    mode: "{{ item.mode | default(0755) }}"
  with_items:
    - path: "/etc/gridinit.d/{{ openio_account_namespace }}"
    - path: "{{ openio_account_sysconfig_dir }}/{{ openio_account_servicename }}"
    - path: "/etc/oio/sds/{{ openio_account_namespace }}/watch"
    - path: "/var/log/oio/sds/{{ openio_account_namespace }}/{{ openio_account_servicename }}"
      owner: "{{ syslog_user }}"
      mode: "0750"
  tags: install

- name: Generate configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: openio
    group: openio
    mode: 0644
  with_items:
    - src: "account.conf.j2"
      dest: "{{ openio_account_sysconfig_dir }}/\
        {{ openio_account_servicename }}/{{ openio_account_servicename }}.conf"
    - src: "gridinit_account.conf.j2"
      dest: "{{ openio_account_gridinit_dir }}/{{ openio_account_gridinit_file_prefix }}\
        {{ openio_account_servicename }}.conf"
    - src: "watch-account.yml.j2"
      dest: "{{ openio_account_sysconfig_dir }}/watch/{{ openio_account_servicename }}.yml"
  register: _account_conf

- name: restart account
  shell: |
    gridinit_cmd reload
    gridinit_cmd restart  {{ openio_account_namespace }}-{{ openio_account_servicename }}
  when:
    - _account_conf.changed
    - not openio_account_provision_only
  tags: configure
...
